### ISSUE TITLE
Fortnite replay reader

### ISSUE THREAD

**Issue by fredimachado** [tpatel/fortnite-replay-reader#2]
Hey Thibaut!

I'm writing a Fortnite replay reader and I think it might be interesting to you: https://github.com/fredimachado/FortniteReplayReader

Sorry about creating an issue, but I didn't know how to contact you.

**Comment by tpatel** [comment]
Hi Fredi!

You can ping me on twitter so we can chat: https://twitter.com/thibpat

Talk to you later!
